import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import Development from "@/components/Development";
import Film from "@/components/Film";
import GridImage from "@/components/GridImage";
import Form from "@/components/Form";
import PopUp from "@/components/PopUp";
import Help from "@/components/Help";
import Message from "@/components/Message";
import Mind from "@/components/Mind";
import Photo from "@/components/Photo";
import Progress from "@/components/Progress";
import Reviews from "@/components/Reviews";
import RoundButton from "@/components/RoundButton";
import Songs from "@/components/Songs";
import Tools from "@/components/Tools";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Development />
        <Film />
        <GridImage />
        <Form />
        <Help />
        <Mind />
        <Message />
        <Photo />
        <Progress />
        <Reviews />
        <RoundButton />
        <Songs />
        <Tools />
      </main>
    </>
  );
}
